### ISSUE TITLE
Advanced example not working

### ISSUE THREAD

**Issue by ShawnOY** [gin-contrib/multitemplate#14]
I move base.html into the /templates/layouts and move index.html into the /templates/includes, both rename to *.tmpl, but I got the error message:
```
Dynamic template with name index.tmpl not found
/usr/local/opt/go/libexec/src/runtime/panic.go:505 (0x102ad78)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-contrib/multitemplate/dynamic.go:141 (0x14dff3e)
	DynamicRender.Instance: panic(fmt.Sprintf("Dynamic template with name %s not found", name))
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-gonic/gin/context.go:605 (0x14cfcd3)
	(*Context).HTML: instance := c.engine.HTMLRender.Instance(name, obj)
/Users/shawnoy/Go/src/xforce-platform-line/main.go:15 (0x14e17a2)
	main.func1: c.HTML(200, "index.tmpl", gin.H{
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-gonic/gin/context.go:104 (0x14cd772)
	(*Context).Next: c.handlers[c.index](c)
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-gonic/gin/recovery.go:45 (0x14dd309)
	RecoveryWithWriter.func1: c.Next()
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-gonic/gin/context.go:104 (0x14cd772)
	(*Context).Next: c.handlers[c.index](c)
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-gonic/gin/logger.go:79 (0x14dc726)
	LoggerWithWriter.func1: c.Next()
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-gonic/gin/context.go:104 (0x14cd772)
	(*Context).Next: c.handlers[c.index](c)
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-gonic/gin/gin.go:332 (0x14d48c4)
	(*Engine).handleHTTPRequest: context.Next()
/Users/shawnoy/Go/src/xforce-platform-line/vendor/github.com/gin-gonic/gin/gin.go:296 (0x14d4112)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/opt/go/libexec/src/net/http/server.go:2694 (0x12b3bdb)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/opt/go/libexec/src/net/http/server.go:1830 (0x12afd90)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2361 (0x10569c0)
	goexit: BYTE	$0x90	// NOP
```

I can not found where is wrong 😞

**Comment by qZanity** [comment]
I come across the same issue, Not sure who the author was but they really should test there code before posting it on a popular github repo.

The problem is each time the template is added its using the name of the "layout" which is always base. This simply does not work, and is outright wrong.

I modified the example and changed the structure, to me it makes more sense.

templates/views - this is where i keep all my pages.
templates/layouts - this is where i keep any layouts IE: base.tmpl
templates/includes - this is where i keep any includes for the templates, IE navigation menu etc.

I then changed the loadtemplates function to this, Notice the static definition of base.tmpl. We could add base.tmpl to views, but i feel its better this way

```
func loadTemplates(templatesDir string) multitemplate.Renderer {
	r := multitemplate.NewRenderer()

	layouts, err := filepath.Glob(templatesDir + "/views/*.tmpl")
	if err != nil {
		panic(err.Error())
	}

	includes, err := filepath.Glob(templatesDir + "/includes/*.tmpl")
	if err != nil {
		panic(err.Error())
	}

	for _, layout := range layouts {
		files := append([]string{"templates/layouts/base.tmpl", layout}, includes...)
		r.Add(filepath.Base(layout), template.Must(template.ParseFiles(files...)))
	}
	return r
}
```

**Comment by appleboy** [comment]
See https://github.com/gin-contrib/multitemplate/blob/master/example/advanced/example.go

**Comment by ikropotov** [comment]
I think it's related here:

https://github.com/gin-contrib/multitemplate/blob/41d1d62d1df32090eb009f4741d9eef6feff6967/example/advanced/example.go#L28

I've been using this example to run on my locale in debug mode, and for different routes and different templates it's been loading only first template to render.
I managed to fix it with `r := multitemplate.New()` as pointed here:

https://github.com/gin-gonic/contrib/tree/master/renders/multitemplate

**Comment by fahmyabdul** [comment]
I still got this error :
`html/template:base.tmpl.html:5:12: no such template "content"`
if I use "DebugMode" or didn't set it to "ReleaseMode", 
it's alright if I use ReleaseMode, but ReleaseMode didn't autoreload template if there's change in template
