### ISSUE TITLE
Engine.SetFuncMap can not pass FuncMap into multitemplate render

### ISSUE THREAD

**Issue by erinus** [gin-contrib/multitemplate#7]
router.SetFuncMap(template.FuncMap{
	"formatAsDate": formatAsDate,
})

var render multitemplate.Render
render = multitemplate.New()
render.AddFromFiles("index", "index.tpl", "app.tpl")

But function 'formatAsDate' cannot be passed into template 'index'.

Maybe have a some machanism to make multitemplate work with Engine.FuncMap ?

**Comment by tboerger** [comment]
multitemplate always returns the template, so you can add a funcMap anyway. But that have not been possible with the builtin template functions

**Comment by erinus** [comment]
Thanks, I got it.
