### ISSUE TITLE
multi define template ***

### ISSUE THREAD

**Issue by iiinsomnia** [gin-contrib/multitemplate#9]

**Comment by IIInsomnia** [comment]
Error: multi define template ***

**Comment by IIInsomnia** [comment]
r.AddFromFiles("index", "templates/base.html", "templates/index.html")
r.AddFromFiles("article", "templates/base.html", "templates/index.html", "templates/article.html")

Error: multiple definition template ***

**Comment by BenKnigge** [comment]
Add a final comma at the end of the list of files. 

r.AddFromFiles("index", "templates/base.html", "templates/index.html",)
